In [2]:
import numpy as np
print(np.array([1, 2, 3]) + 10)


[11 12 13]


In [4]:
import numpy as np

cost_price = np.array([1500, 3000, 5000])

daily_sales = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])

print("Cost Price Array:")
print("Shape:", cost_price.shape)
print("Dimensions:", cost_price.ndim)

print("\nDaily Sales Array:")
print("Shape:", daily_sales.shape)
print("Dimensions:", daily_sales.ndim)


Cost Price Array:
Shape: (3,)
Dimensions: 1

Daily Sales Array:
Shape: (3, 4)
Dimensions: 2


In [5]:
import numpy as np

daily_sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

cost_price = np.array([100, 150, 200])

print("Original Daily Sales:\n", daily_sales)

daily_sales_bonus = daily_sales + 2
print("\nDaily Sales after adding bonus units:\n", daily_sales_bonus)

scaled_sales = np.sqrt(daily_sales_bonus)
print("\nSquare root of sales values:\n", scaled_sales)


Original Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Daily Sales after adding bonus units:
 [[12 14 11 13]
 [10  9 12 11]
 [17 16 18 15]]

Square root of sales values:
 [[3.46410162 3.74165739 3.31662479 3.60555128]
 [3.16227766 3.         3.46410162 3.31662479]
 [4.12310563 4.         4.24264069 3.87298335]]


In [6]:
sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

print("Sales Data:\n", sales)

smartwatches_sales = sales[1, :]
print("\nSmartwatches sales for all days:\n", smartwatches_sales)

first_two_days = sales[:, 0:2]
print("\nSales for all products (Monday & Tuesday):\n", first_two_days)

speakers_thursday = sales[2][3]
print("\nSpeakers sales on Thursday:\n", speakers_thursday)

sub_array = sales[0:2, 0:2]
print("\n2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):\n", sub_array)


Sales Data:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Smartwatches sales for all days:
 [ 8  7 10  9]

Sales for all products (Monday & Tuesday):
 [[10 12]
 [ 8  7]
 [15 14]]

Speakers sales on Thursday:
 13

2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):
 [[10 12]
 [ 8  7]]


In [8]:
daily_sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

print("Original 3x4 Daily Sales:\n", daily_sales)

flattened_sales = daily_sales.reshape(12)
print("\nFlattened 1D array:\n", flattened_sales)

reshaped_sales = daily_sales.reshape(2, 6)
print("\nReshaped 2x6 matrix:\n", reshaped_sales)

discount_percentages = np.linspace(0, 100, 10)
print("\nDiscount Percentages:\n", discount_percentages)


Original 3x4 Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Flattened 1D array:
 [10 12  9 11  8  7 10  9 15 14 16 13]

Reshaped 2x6 matrix:
 [[10 12  9 11  8  7]
 [10  9 15 14 16 13]]

Discount Percentages:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [12]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# ---------- Task A1: Metadata Discovery ----------

# Shape of the array
print("Shape:", marks.shape)

# Total number of elements
print("Total elements:", marks.size)

# Data type of elements
print("Data type:", marks.dtype)


# ---------- Task A2: Data Indexing & Slicing ----------

# All marks for the 2nd student (index 1)
print("2nd student marks:", marks[1])

# All marks for the 3rd subject across all students (index 2)
print("3rd subject marks:", marks[:, 2])

# Specific mark for Student 1 in Subject 2 (row 0, col 1)
print("Student 1, Subject 2 mark:", marks[0, 1])

Shape: (5, 3)
Total elements: 15
Data type: int64
2nd student marks: [45 60 55]
3rd subject marks: [90 55 95 35 75]
Student 1, Subject 2 mark: 85


In [13]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# ---------- Task B1: Means and Averages ----------

# Average marks for each student (row-wise)
student_avg = marks.mean(axis=1)
print("Average marks per student:", student_avg)

# Average marks for each subject (column-wise)
subject_avg = marks.mean(axis=0)
print("Average marks per subject:", subject_avg)


# ---------- Task B2: Filtering Top Performers ----------

# Students whose average marks >= 80
top_students = np.where(student_avg >= 80)[0] + 1  # +1 for student numbering
print("Top performing students (avg >= 80):", top_students)


# ---------- Task B3: Global Adjustments (Broadcasting) ----------

# Add 5 grace marks to every subject for every student
updated_marks = marks + 5
print("Updated marks after grace:\n", updated_marks)

Average marks per student: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Average marks per subject: [61.2 69.4 70. ]
Top performing students (avg >= 80): [1 3]
Updated marks after grace:
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [14]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# ---------- Task C1: Pass / Fail Mapping ----------

# Pass = 1 if mark >= 50, Fail = 0 if mark < 50
status_matrix = np.where(marks >= 50, 1, 0)
print("Pass / Fail Status Matrix:\n", status_matrix)


# ---------- Task C2: Data Cleaning ----------

# Replace all marks below 40 with 0
cleaned_marks = np.where(marks < 40, 0, marks)
print("Cleaned Marks Matrix:\n", cleaned_marks)

Pass / Fail Status Matrix:
 [[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]
Cleaned Marks Matrix:
 [[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [15]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# Calculate average marks per student
student_avg = marks.mean(axis=1)

# ---------- Task D1: Grade Allocation ----------

# Initialize score array with zeros
grade_score = np.zeros_like(student_avg)

# Apply grading rules
grade_score = np.where(student_avg >= 85, 10,
               np.where(student_avg >= 70, 8,
               np.where(student_avg >= 50, 6, 0)))

print("Student Averages:", student_avg)
print("Grade Scores:", grade_score)

Student Averages: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Grade Scores: [ 8  6 10  0  8]


In [4]:
import numpy as np

# Create electricity array
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)


print("Shape:", electricity.shape)
print("Number of Dimensions:", electricity.ndim)
print("Total Number of Elements:", electricity.size)
print("Data Type:", electricity.dtype)


# Average electricity per hostel
avg_per_hostel = np.mean(electricity, axis=1)

# Maximum usage per hostel
max_per_hostel = np.max(electricity, axis=1)

# Hostel with highest average usage
highest_avg_hostel = np.argmax(avg_per_hostel)

print("Average per Hostel:", avg_per_hostel)
print("Max per Hostel:", max_per_hostel)
print("Hostel with Highest Average Usage:", highest_avg_hostel)


# Total electricity per day
total_per_day = np.sum(electricity, axis=0)

# Day with highest total consumption
highest_day = np.argmax(total_per_day)

print("Total per Day:", total_per_day)
print("Day with Highest Consumption:", highest_day)

Electricity Data:
 [[290 453 202 627 375 468 553]
 [299 310 454 361 186 428 300]
 [576 469 613 451 484 628 305]
 [515 473 254 523 368 194 517]]
Shape: (4, 7)
Number of Dimensions: 2
Total Number of Elements: 28
Data Type: int32
Average per Hostel: [424.         334.         503.71428571 406.28571429]
Max per Hostel: [627 454 628 523]
Hostel with Highest Average Usage: 2
Total per Day: [1680 1705 1523 1962 1413 1718 1675]
Day with Highest Consumption: 3


In [5]:
import numpy as np

# Part A
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)

# Part C
penalized_usage = np.where(electricity > 550,
                           electricity * 1.20,
                           electricity)

print("\nPenalized Usage:\n", penalized_usage)

Electricity Data:
 [[598 482 593 214 422 273 623]
 [481 398 637 343 353 320 584]
 [291 593 587 298 451 251 218]
 [232 517 487 259 261 146 621]]

Penalized Usage:
 [[717.6 482.  711.6 214.  422.  273.  747.6]
 [481.  398.  764.4 343.  353.  320.  700.8]
 [291.  711.6 704.4 298.  451.  251.  218. ]
 [232.  517.  487.  259.  261.  146.  745.2]]


In [6]:
# Weekly average per hostel
hostel_avg = np.mean(electricity, axis=1).reshape(4, 1)

# Boolean comparison matrix
comparison_matrix = electricity > hostel_avg

print("Hostel Weekly Averages:\n", hostel_avg)
print("\nComparison Matrix (True = Above Avg):\n", comparison_matrix)

Hostel Weekly Averages:
 [[457.85714286]
 [445.14285714]
 [384.14285714]
 [360.42857143]]

Comparison Matrix (True = Above Avg):
 [[ True  True  True False False False  True]
 [ True False  True False False False  True]
 [False  True  True False  True False False]
 [False  True  True False False False  True]]


In [8]:
import numpy as np

# =========================
# PART A – ARRAY CREATION
# =========================

# Task A1
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)

# Task A2 – Array Attributes
print("\n--- Array Attributes ---")
print("Shape:", electricity.shape)
print("Dimensions:", electricity.ndim)
print("Total Elements:", electricity.size)

Electricity Data:
 [[563 618 491 333 455 221 408]
 [251 194 144 282 644 243 575]
 [385 367 618 488 314 300 532]
 [289 312 509 561 624 275 156]]

--- Array Attributes ---
Shape: (4, 7)
Dimensions: 2
Total Elements: 28
