In [2]:
import numpy as np
print(np.array([1, 2, 3]) + 10)


[11 12 13]


In [4]:
import numpy as np

cost_price = np.array([1500, 3000, 5000])

daily_sales = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])

print("Cost Price Array:")
print("Shape:", cost_price.shape)
print("Dimensions:", cost_price.ndim)

print("\nDaily Sales Array:")
print("Shape:", daily_sales.shape)
print("Dimensions:", daily_sales.ndim)


Cost Price Array:
Shape: (3,)
Dimensions: 1

Daily Sales Array:
Shape: (3, 4)
Dimensions: 2


In [5]:
import numpy as np

daily_sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

cost_price = np.array([100, 150, 200])

print("Original Daily Sales:\n", daily_sales)

daily_sales_bonus = daily_sales + 2
print("\nDaily Sales after adding bonus units:\n", daily_sales_bonus)

scaled_sales = np.sqrt(daily_sales_bonus)
print("\nSquare root of sales values:\n", scaled_sales)


Original Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Daily Sales after adding bonus units:
 [[12 14 11 13]
 [10  9 12 11]
 [17 16 18 15]]

Square root of sales values:
 [[3.46410162 3.74165739 3.31662479 3.60555128]
 [3.16227766 3.         3.46410162 3.31662479]
 [4.12310563 4.         4.24264069 3.87298335]]


In [6]:
sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

print("Sales Data:\n", sales)

smartwatches_sales = sales[1, :]
print("\nSmartwatches sales for all days:\n", smartwatches_sales)

first_two_days = sales[:, 0:2]
print("\nSales for all products (Monday & Tuesday):\n", first_two_days)

speakers_thursday = sales[2][3]
print("\nSpeakers sales on Thursday:\n", speakers_thursday)

sub_array = sales[0:2, 0:2]
print("\n2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):\n", sub_array)


Sales Data:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Smartwatches sales for all days:
 [ 8  7 10  9]

Sales for all products (Monday & Tuesday):
 [[10 12]
 [ 8  7]
 [15 14]]

Speakers sales on Thursday:
 13

2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):
 [[10 12]
 [ 8  7]]


In [7]:
daily_sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

print("Original 3x4 Daily Sales:\n", daily_sales)

flattened_sales = daily_sales.reshape(12)
print("\nFlattened 1D array:\n", flattened_sales)

reshaped_sales = daily_sales.reshape(2, 6)
print("\nReshaped 2x6 matrix:\n", reshaped_sales)

discount_percentages = np.linspace(0, 100, 10)
print("\nDiscount Percentages:\n", discount_percentages)


Original 3x4 Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Flattened 1D array:
 [10 12  9 11  8  7 10  9 15 14 16 13]

Reshaped 2x6 matrix:
 [[10 12  9 11  8  7]
 [10  9 15 14 16 13]]

Discount Percentages:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
